name: validate files
on:
  push:
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  validate-files:
    runs-on: ubuntu-latest
    steps:
      - name: get-repo-code
        uses: actions/checkout@v4

      - name: validate-html-files
        working-directory: second-example
        run: test -f index.html

      - name: validate-js-files
        working-directory: second-example
        run: test -f index.js