name : first
on: workflow_dispatch
jobs:
  firstjobs:
    runs-on: ubuntu-latest
    steps:
      - name: github action
        run: echo "this is first work flow github action"

      - name: bye github
        run: echo "bye github action"
