name: second-workflow
on: push
jobs:
    hello-job:
      run-on: ubuntu-latest
      steps:
        name: "welcome"
        run: echo "this is second one"

    bye-job:
      run-on: ubuntu-latest
      steps:
        name: "Bye rony"
        run: echo "this is another job"
