name: validate files
on:
  push:
  workflow_dispatch:

jobs:
  validate-files:
    runs-on: ubuntu-latest
    steps:
      - name: get-repo-code
        uses: actions/checkout@v4

      - name: validate-html-files
        run: test -f second-example/index.html

      - name: validate-js-files
        run: test -f second-example/index.js
      - name: validate-code-files
        run: node --check second-example/index.js
